version: "3.8"

services:
  composer:
    image: composer:2.1.9
    entrypoint: composer
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todo_bdd
    volumes:
      - ./database:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
